name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Moves REST docs in temporary directory
      - name: Compile docs
        run: |
          mkdir ./rest-api-docs
          cp ./plentymarkets/openApiV3/openApiV3WithExamples.min.json ./rest-api-docs/openApiV3WithExamples.min.json
          cp ./plentyBase/openApiV2/openApiV2.json ./rest-api-docs/plentyBase-OpenApiV3.json
  
      - name: Upload files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          SOURCE_DIR: './rest-api-docs'
          DEST_DIR: './rest-api-docs'
          AWS_REGION: 'eu-central-1'
